### ISSUE TITLE
Invalid yaml for routes.yml

### ISSUE THREAD

**Issue by gmenuel** [thingsboard/thingsboard-pe-k8s#19]
Hello,
I've noticed that the yaml file https://github.com/thingsboard/thingsboard-pe-k8s/blob/master/common/routes.yml is invalid because of the 4 dashes at the end of the file. Only 3 are needed in yaml. This cause problem in our workflow since we are using kustomize to install the kubernetes resources.

**Comment by mistadave** [comment]
i received an error when i tried to run the Thingsboard PE scripts on kubernetes version 1.20.9

command to run the routes.yml
```bash
kubectl apply -f common/routes.yml --dry-run=server
error: error parsing common/routes.yml: invalid Yaml document separator: -

Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-16T01:10:02Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

By deleting one or all dashes, it will run without any error.

Also received a warning of deprecated version in v1.19+.

```bash
kubectl apply -f common/routes.yml --dry-run=server
Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

**Comment by ashvayka** [comment]
Please consider using new scripts for AWS EKS / GKE / Azure. They have the new version of routes.yml files.
