### ISSUE TITLE
AWS EKS MQTT Connection not possible

### ISSUE THREAD

**Issue by willsamu** [thingsboard/thingsboard-pe-k8s#25]
After following the [instructions for setting up the deployment on AWS EKS ](https://thingsboard.io/docs/user-guide/install/pe/cluster/aws-eks-cluster-setup/)infrastructure it is not possible to connect via MQTT as there is no public endpoint available.

I have tried configuring the `tb-mqtt-transport`-Service in `common/thingsboard.yml` to be of type `LoadBalancer`, which creates a classic loadbalancer additionally to the default network loadbalancer. From there, I could forward port 1883 to the `tb-mqtt-transport` to process MQTT connections.

However, this does not work with MQTT over SSL. I generated a self signed server certificate using [these instuctions](https://thingsboard.io/docs/user-guide/mqtt-over-ssl/) with the classic load balancers DNS-Name as CN value and it's resolved IP-addreses as SAN. Adding the resulting `.jks`-file as Secret to the Kubernetes Cluster and mounting it to `/config/mqttserver.jks` workes fine, but whether I try to send a `PUBLISH` message using mosquitto_pub from another pod inside the cluster or from a host outside the cluster, the message `TLS Error` shows up.

Can you please provide an appropriate setup for the EKS Cluster using MQTT over SSL and update/fix the documentation?

Thanks a lot in Advance!

**Comment by ashvayka** [comment]
Please consider using new [guide](https://thingsboard.io/docs/user-guide/install/pe/cluster/aws-eks-setup/) which includes steps to setup corresponding MQTT Load Balancers.
