### ISSUE TITLE
[BUG] Error: ErrImagePull

### ISSUE THREAD

**Issue by benoguz** [thingsboard/thingsboard-pe-k8s#43]
I have problem for Thingsboard PE installation. 
I followed all the steps :
https://thingsboard.io/docs/user-guide/install/pe/cluster/minikube-cluster-setup/
I have no problems pulling docker images from the command line in local but when I run the installation script I get the following error:
Failed to pull image "store/thingsboard/tb-pe-node:3.3.4.1PE"
failed size validation: 2707 != 3465: failed precondition.

There is an open issue (similar or same) on the link for community version: https://github.com/thingsboard/thingsboard/issues/6176

Thanks in advance.

Server Environment:

> On Premise in ubuntu 20.04.3

>  Kubernetes v1.21.11

**Comment by ashvayka** [comment]
We have replaced links to docker store t oa regular docker hub links: ( "store/thingsboard/tb-pe-node:3.3.4.1PE" -> "thingsboard/tb-pe-node:3.3.4.1PE"). Now the issue should be resolved.

**Comment by Ultrazombie** [comment]
Hello @benoguz,
Did you solve your problem by changing the image location?

**Comment by benoguz** [comment]
Thanks it is solved :)
