### ISSUE TITLE
add docker login as a required step for AWS K8s deployment

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard-pe-k8s#7]
You should add a step instructing user to checkout docker images and then adding the docker login secret to k8s

as described in this guide:

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by t0mmyz7** [comment]
oh I just saw k8s-upload-docker-credentials.sh 

so I guess it didn't work because I wasn't logged in at the time, so you should add a step just about user having to checkout images and docker login :) :) 

awesome work on this k8s stuff, really great!

**Comment by ashmidt-thingsboard** [comment]
We have this step on our website but not in the README. 
I'll add that to the README soon.
Thanks a lot.

**Comment by t0mmyz7** [comment]
my pleasure
