### ISSUE TITLE
how to secure aws k8s thingsboard install with letsencrypt?

### ISSUE THREAD

**Issue by t0mmyz7** [thingsboard/thingsboard-pe-k8s#8]
Hi

this might be common k8s knowledge, but I am novice so perhaps you can assist me with this, how do I install letsencrypt certificates and even better, setup auto renew for it ?

thanks in advance

**Comment by t0mmyz7** [comment]
@ashmidt-thingsboard any advice on this? I been trying different things on AWS but can't get it to work.

**Comment by t0mmyz7** [comment]
I am thinking somehow need to merge the yaml from here:
https://kubernetes.github.io/ingress-nginx/deploy/#aws

with aws/ingress.yaml 

To add TLS termination to the ingress, and with their example they connect it to a certificate from ACM and also to the load balancer.

**Comment by t0mmyz7** [comment]
@ashmidt-thingsboard 

any chance you can add SSL instructions to the k8s deployment on EKS or other platforms? It can be great help, thanks!

**Comment by t0mmyz7** [comment]
So any help on this ?

**Comment by ashmidt-thingsboard** [comment]
Hello @t0mmyz7,
This doesn`t apply to the thingsboard installation.
I have used a letsencrypt with a eks and a nginx-ingress. And I used this instruction - https://cert-manager.io/docs/tutorials/acme/ingress/

**Comment by t0mmyz7** [comment]
10x
